### ISSUE TITLE
Base regen rate on real time rather than game time.

### ISSUE THREAD

**Issue by darkling3100** [JessebotX/StardewMods#7]
**Feature for which mod**: HealthStaminaRegen

**Explain Feature**: Would you be able to add an option to base the regen rate off of real/system time? Neither regen option works when game time is paused.

**Comment by JessebotX** [comment]
So you just want it to regenerate health and stamina when the game is paused?

**Comment by JessebotX** [comment]
If what you mean is you want health and stamina to regenerate even if the game is paused. Update [2.0.1](https://www.nexusmods.com/stardewvalley/mods/3207) adds a new config option called `IgnorePause` which is false by default but will let you regen health even if a menu is opened, a cutscene is playing, etc.

See [release notes](https://github.com/JessebotX/StardewValleyMods/blob/master/HealthStaminaRegen/changelog.md) and [config instructions](https://github.com/JessebotX/StardewValleyMods/blob/master/HealthStaminaRegen/README.md#configjson) OR use [Generic Mod Config Menu](https://www.nexusmods.com/stardewvalley/mods/5098) for more
